[metro_trem]
[metro_trem.rj]
urls = [
  "https://pt.wikipedia.org/wiki/Metr%C3%B4_do_Rio_de_Janeiro",
  "https://pt.wikipedia.org/wiki/SuperVia",
]

[metro_trem.sp]
urls = ["https://pt.wikipedia.org/wiki/Metr%C3%B4_de_S%C3%A3o_Paulo"]

[sites]
[sites.vivareal]
site = "https://www.vivareal.com.br"
api = "glue-api.vivareal.com"
portal = "VIVAREAL"

[sites.zapimoveis]
site = "https://www.zapimoveis.com.br"
api = "glue-api.zapimoveis.com.br"
portal = "ZAP"
