http://localhost:5000/locations/barra da tijuca



###
http://localhost:5000/listings/abc/abc/Rio de Janeiro/BR>Rio de Janeiro>NULL>Rio de Janeiro>Zona Oeste>Barra da Tijuca/Barra da Tijuca/Rio de Janeiro/RJ/Zona Oeste



###
http://localhost:5000/listings/RENTAL/USED/Rio de Janeiro/BR>Rio de Janeiro>NULL>Rio de Janeiro>Zona Oeste>Barra da Tijuca/Barra da Tijuca/Rio de Janeiro/RJ/Zona Oeste

