[DEFAULT]
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "postgres"
POSTGRES_DB = "listing"
POSTGRES_PORT = 5432
BACKEND_PORT = 5000

[DEVELOPMENT]
POSTGRES_HOST = "localhost"
BACKEND_HOST = "localhost"

[PRODUCTION]
POSTGRES_HOST = "db"
BACKEND_HOST = "fetch"
