version: "3.9"
services:
    db:
        image: postgres
        restart: always
        env_file: 
            - ./.env
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5


    fetch:
        hostname: fetch
        build: 
            context: ./fetch/
            dockerfile: Dockerfile
        restart: always
        env_file: 
            - ./.env
        ports:
            - ${BACKEND_PORT}:${BACKEND_PORT}
        networks:
            - network
        depends_on:
            db:
                condition: service_healthy

    front:
        build: 
            context: ./front/
            dockerfile: Dockerfile
        restart: always
        env_file:
            - ./.env
        ports:
            - ${FRONT_PORT}:${FRONT_PORT}
        networks:
            - network
        depends_on:
            db:
                condition: service_healthy
        
networks: 
    network:
        driver: bridge

volumes:
    pgdata:
