version: "3.9"
services:
    db:
        image: postgres
        restart: always
        env_file: 
            - ./.env
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5


    app:
        build: 
            context: ./
            dockerfile: ./fetch/Dockerfile
        restart: always
        env_file: 
            - ./.env
        ports:
            - ${PORT}:${PORT}
        networks:
            - network
        depends_on:
            db:
                condition: service_healthy
        
networks: 
    network:

volumes:
    pgdata:
