version: "3.9"
services:
    db:
        image: postgres
        restart: always
        env_file:
            - ./.env
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        ports:
            - "${POSTGRES_PORT}:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5

    fetch:
        hostname: fetch
        build:
            dockerfile: ./fetch/Dockerfile
        restart: always
        env_file:
            - ./.env
        ports:
            - ${BACKEND_PORT}:${BACKEND_PORT}
        networks:
            - network
        depends_on:
            db:
                condition: service_healthy

    front:
        build:
            dockerfile: ./front/Dockerfile
        restart: always
        env_file:
            - ./.env
        ports:
            - ${FRONT_PORT}:${FRONT_PORT}
        networks:
            - network

    model:
        build:
            dockerfile: ./model/Dockerfile
        restart: always
        env_file:
            - ./.env
        ports:
            - ${MODEL_PORT}:${MODEL_PORT}
        networks:
            - network
        healthcheck:
            test: ["CMD-SHELL", "curl", "http://localhost:${MODEL_PORT}/health"]
            interval: 10s
            retries: 5
            start_period: 1s
            timeout: 3s
        depends_on:
            db:
                condition: service_healthy

networks:
    network:
        driver: bridge

volumes:
    pgdata:
