name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Verify dependencies
      working-directory: ./fetch
      run: go mod verify

    - name: Build
      working-directory: ./fetch
      run: go build -v ./...

    - name: Run go vet
      working-directory: ./fetch
      run: go vet ./...

    - name: Install staticcheck
      working-directory: ./fetch
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      working-directory: ./fetch
      run: staticcheck ./...

    - name: Install golint
      working-directory: ./fetch
      run: go install golang.org/x/lint/golint@latest

    - name: Run golint
      working-directory: ./fetch
      run: golint ./...

    - name: Run tests
      working-directory: ./fetch
      run: go test -race -vet=off ./...
